import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { symbolLabel } from "./grading";

interface ReportCardSubject {
  name: string;
  score: number;
  maxMarks: number;
  percentage: number;
  symbol: string;
}

interface ReportCardData {
  schoolName: string;
  studentName: string;
  studentNumber: string;
  grade: string;
  className: string;
  academicYear: string;
  term: string;
  subjects: ReportCardSubject[];
  overallAverage: number;
  overallSymbol: string;
  comments?: string;
}

export async function generateReportCardPdf(data: ReportCardData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const { width, height } = page.getSize();
  let y = height - 50;

  const drawText = (text: string, x: number, size: number, bold = false) => {
    page.drawText(text, {
      x,
      y,
      size,
      font: bold ? fontBold : font,
      color: rgb(0.1, 0.1, 0.2),
    });
    y -= size + 6;
  };

  // Header
  page.drawRectangle({
    x: 0,
    y: height - 80,
    width,
    height: 80,
    color: rgb(0.11, 0.3, 0.43),
  });
  page.drawText(data.schoolName, {
    x: 50,
    y: height - 45,
    size: 18,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  page.drawText("LEARNER REPORT CARD", {
    x: 50,
    y: height - 65,
    size: 11,
    font,
    color: rgb(0.9, 0.9, 0.9),
  });

  y = height - 110;
  drawText(`Student: ${data.studentName}`, 50, 12, true);
  drawText(`Student No: ${data.studentNumber}`, 50, 10);
  drawText(`Grade: ${data.grade}  |  Class: ${data.className}`, 50, 10);
  drawText(`Academic Year: ${data.academicYear}  |  Term: ${data.term}`, 50, 10);

  y -= 10;
  // Table header
  const cols = [50, 220, 320, 380, 450];
  page.drawText("Subject", { x: cols[0], y, size: 10, font: fontBold, color: rgb(0.1, 0.3, 0.43) });
  page.drawText("Score", { x: cols[1], y, size: 10, font: fontBold, color: rgb(0.1, 0.3, 0.43) });
  page.drawText("%", { x: cols[2], y, size: 10, font: fontBold, color: rgb(0.1, 0.3, 0.43) });
  page.drawText("Symbol", { x: cols[3], y, size: 10, font: fontBold, color: rgb(0.1, 0.3, 0.43) });
  y -= 5;
  page.drawLine({ start: { x: 50, y }, end: { x: width - 50, y }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
  y -= 15;

  for (const sub of data.subjects) {
    page.drawText(sub.name, { x: cols[0], y, size: 9, font });
    page.drawText(`${sub.score}/${sub.maxMarks}`, { x: cols[1], y, size: 9, font });
    page.drawText(`${sub.percentage}%`, { x: cols[2], y, size: 9, font });
    page.drawText(sub.symbol, { x: cols[3], y, size: 9, font: fontBold });
    y -= 16;
  }

  y -= 10;
  page.drawLine({ start: { x: 50, y: y + 5 }, end: { x: width - 50, y: y + 5 }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
  y -= 10;
  drawText(`Overall Average: ${data.overallAverage}%  (Symbol ${data.overallSymbol} — ${symbolLabel(data.overallSymbol)})`, 50, 11, true);

  if (data.comments) {
    y -= 5;
    drawText("Comments:", 50, 10, true);
    const words = data.comments.split(" ");
    let line = "";
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      if (test.length > 80) {
        drawText(line, 50, 9);
        line = word;
      } else {
        line = test;
      }
    }
    if (line) drawText(line, 50, 9);
  }

  y = 80;
  page.drawText("Generated by SchoolHub SA — Cyber Developers", {
    x: 50,
    y,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
  page.drawText(`Generated: ${new Date().toLocaleDateString("en-ZA")}`, {
    x: 50,
    y: y - 12,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return doc.save();
}
