services:
  postgres:
    image: postgres:16-alpine
    container_name: schoolhub-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schoolhub_sa
    volumes:
      - schoolhub_pgdata:/var/lib/postgresql/data

volumes:
  schoolhub_pgdata:
